// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	AlertID   int32
	WebsiteID int32
	Timestamp pgtype.Timestamptz
	Type      pgtype.Text
	Message   pgtype.Text
	Resolved  pgtype.Bool
}

type StatusCheck struct {
	CheckID      int32
	WebsiteID    int32
	Timestamp    pgtype.Timestamptz
	StatusCode   pgtype.Int4
	ResponseTime pgtype.Int4
	Status       pgtype.Text
	Details      pgtype.Text
}

type Website struct {
	WebsiteID     int32
	Url           string
	Name          pgtype.Text
	CheckInterval pgtype.Int4
}
